# This file was generated by GoReleaser. DO NOT EDIT.
cask "restui" do
  name "restui"
  desc "API client in your terminal"
  homepage "https://github.com/arfadmuzali/restui"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restui"

  on_macos do
    on_intel do
      url "https://github.com/arfadmuzali/restui/releases/download/v#{version}/restui_Darwin_x86_64.tar.gz"
      sha256 "3d45e27dc8fe972235edfb8b99deec0102e00f598f5bff44094fa24281ee1510"
    end
    on_arm do
      url "https://github.com/arfadmuzali/restui/releases/download/v#{version}/restui_Darwin_arm64.tar.gz"
      sha256 "8c2d5a50619c7da7b22d055be1dff84ae2f2e1275abd99e679465383553b700a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arfadmuzali/restui/releases/download/v#{version}/restui_Linux_x86_64.tar.gz"
      sha256 "a2a6dcd3a3bc519a72208cde5519c033aac86e6f603a925c1ae85bba8ba96fee"
    end
  end

  # No zap stanza required
end
