# This file was generated by GoReleaser. DO NOT EDIT.
cask "restui" do
  version "1.3.1"

  on_macos do
    on_intel do
      url "https://github.com/arfadmuzali/restui/releases/download/v#{version}/restui_Darwin_x86_64.tar.gz"
      sha256 "b56b9cd91d76145ec34d53db962f0e3b143e7eb0e58026526691460ff5a3c52f"
    end
    on_arm do
      url "https://github.com/arfadmuzali/restui/releases/download/v#{version}/restui_Darwin_arm64.tar.gz"
      sha256 "2b37b77213df5660b6e234c5cd73b43bd2143431b39a2caaab75845ed7c34b5f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arfadmuzali/restui/releases/download/v#{version}/restui_Linux_x86_64.tar.gz"
      sha256 "77e11b050c86bf0a5450df048b58657e4b1e01df99e9470eac3afd08ffe56745"
    end
    on_arm do
      url "https://github.com/arfadmuzali/restui/releases/download/v#{version}/restui_Linux_arm64.tar.gz"
      sha256 "d82af3f94fa1a89cd72d8e943acbd14ed560d7472e183aad71ca23765f8ebcb9"
    end
  end

  name "restui"
  desc "API client in your terminal"
  homepage "https://github.com/arfadmuzali/restui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restui"

  # No zap stanza required

end
